### ISSUE TITLE
User Story: Display game records

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/tactical-rashers#21]
User story for concern of front end.

**User Type**
Any user

**Functionality**
Display games played/won/lost

**Benefit**
Allows users to see the historic records of other players

---
**Acceptance Criteria**
- [ ] A logged in user can view their own game history on their profile
- [ ] A logged in user can view other users' records by visiting their profile
- [ ] A logged out user can view other users' records by visiting their profile
